spring:
  application:
    name: gateway-service
  config:
    import: 'optional:eureka:,configserver:'
  cloud:
    config:
      uri: http://localhost:8761
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.1
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true